<?php if (empty($this->users)): ?>
    Список пользователей пуст.
<?php endif; ?>

<?php if (!empty($this->users)): ?>
    <?php
        /** @var \Application\Entity\User $user */
        foreach ($this->users as $user):
    ?>
        Id: <?php echo $this->escapeHtml($user->getId()); ?>
        Name: <?php echo $this->escapeHtml($user->getName()); ?>
        <br/>
    <?php endforeach; ?>
<?php endif; ?>